(function() {var implementors = {};
implementors["ascii"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='ascii/struct.AsciiStr.html' title='struct ascii::AsciiStr'>AsciiStr</a>",];
implementors["itertools"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html' title='struct std::ffi::c_str::CStr'>CStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html' title='struct std::ffi::os_str::OsStr'>OsStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/path/struct.Path.html' title='struct std::path::Path'>Path</a>",];
implementors["lazy_static"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html' title='struct std::ffi::c_str::CStr'>CStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html' title='struct std::ffi::os_str::OsStr'>OsStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/path/struct.Path.html' title='struct std::path::Path'>Path</a>",];
implementors["libc"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html' title='struct std::ffi::c_str::CStr'>CStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html' title='struct std::ffi::os_str::OsStr'>OsStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/path/struct.Path.html' title='struct std::path::Path'>Path</a>",];
implementors["lz4"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html' title='struct std::ffi::c_str::CStr'>CStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html' title='struct std::ffi::os_str::OsStr'>OsStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/path/struct.Path.html' title='struct std::path::Path'>Path</a>",];
implementors["nix"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html' title='struct std::ffi::c_str::CStr'>CStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html' title='struct std::ffi::os_str::OsStr'>OsStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/path/struct.Path.html' title='struct std::path::Path'>Path</a>",];
implementors["regex_syntax"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html' title='struct std::ffi::c_str::CStr'>CStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html' title='struct std::ffi::os_str::OsStr'>OsStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/path/struct.Path.html' title='struct std::path::Path'>Path</a>",];
implementors["serde"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html' title='struct std::ffi::c_str::CStr'>CStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html' title='struct std::ffi::os_str::OsStr'>OsStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/path/struct.Path.html' title='struct std::path::Path'>Path</a>",];
implementors["tantivy"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html' title='struct std::ffi::c_str::CStr'>CStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html' title='struct std::ffi::os_str::OsStr'>OsStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/path/struct.Path.html' title='struct std::path::Path'>Path</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='ascii/ascii_str/struct.AsciiStr.html' title='struct ascii::ascii_str::AsciiStr'>AsciiStr</a>",];
implementors["tempfile"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html' title='struct std::ffi::c_str::CStr'>CStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html' title='struct std::ffi::os_str::OsStr'>OsStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/path/struct.Path.html' title='struct std::path::Path'>Path</a>",];
implementors["void"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html' title='struct std::ffi::c_str::CStr'>CStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html' title='struct std::ffi::os_str::OsStr'>OsStr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html' title='trait collections::borrow::ToOwned'>ToOwned</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/path/struct.Path.html' title='struct std::path::Path'>Path</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
